name: Update AWS S3 Folder Name Annually

on:
  schedule:
    - cron: '0 0 1 1 *' # Runs annually on January 1st at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  update-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Calculate New AWS S3 Folder Name
        id: calculate_folder_name
        run: |
          CURRENT_YEAR=$(date +'%Y')
          NEW_FOLDER_NAME="fda_current_${CURRENT_YEAR}"
          echo "NEW_FOLDER_NAME=${NEW_FOLDER_NAME}" >> $GITHUB_ENV

      - name: Update GitHub Secret
        run: |
          echo $NEW_FOLDER_NAME | gh secret set AWS_S3_FOLDER_NAME --repo ${{ github.repository }} --body -
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NEW_FOLDER_NAME: ${{ env.NEW_FOLDER_NAME }}
